//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDBMSStorage
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoType
    {
        public InfoType()
        {
            this.MovieInfo = new HashSet<MovieInfo>();
            this.PersonInfo = new HashSet<PersonInfo>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<MovieInfo> MovieInfo { get; set; }
        public virtual ICollection<PersonInfo> PersonInfo { get; set; }
    }
}
