//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Storage.EntityDto;

namespace RDBMSStorage
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fakeimdbEntities : DbContext, IDbContext
    {
        public fakeimdbEntities()
            : base("name=fakeimdbEntities")
        {
        }

        //public IDbSet<InfoType> InfoType { get; set; }
        //public IDbSet<MovieInfo> MovieInfo { get; set; }
        //public IDbSet<Movies> Movies { get; set; }
        //public IDbSet<Participate> Participate { get; set; }
        //public IDbSet<People> People { get; set; }
        //public IDbSet<PersonInfo> PersonInfo { get; set; }

        public new IDbSet<T> Set<T>() where T : class
        {
            return base.Set<T>();
        }
    }
}
