//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Storage;

namespace EntityFrameworkStorage
{
    using System;
    using System.Collections.Generic;
    
    public partial class FavouritedMovie : IEntityDto
    {
        public int Id { get; set; }
        public int Movie_Id { get; set; }
        public int FavList_Id { get; set; }
    
        public virtual FavouriteList FavouriteList { get; set; }
        public virtual Movies Movies { get; set; }
    }
}
