//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieInfo : IEntityDto
    {
        public int MovieInfoId { get; set; }
        public string Info { get; set; }
        public string Note { get; set; }
        public int Movie_Id { get; set; }
        public Nullable<int> Type_Id { get; set; }

        public int Id
        {
            set { MovieInfoId = value; }
            get { return MovieInfoId; }
        }
    }
}
