//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies : IEntityDto
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Kind { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> SeasonNumber { get; set; }
        public Nullable<int> EpisodeNumber { get; set; }
        public string SeriesYear { get; set; }
        public Nullable<int> EpisodeOf_Id { get; set; }
    }
}
